build-and-push-to-dockerhub:
	docker build -t mp-test-subscriber-client .
	docker tag mp-test-subscriber-client:latest ddanijeld/mp-test-subscriber-client:latest
	docker push ddanijeld/mp-test-subscriber-client:latest
